name: get stock price

on:
  schedule:
    - cron: "*/5 1-6 * * 1-5"  # 每週一到週五的 1 AM 到 6 AM 每 5 分鐘執行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install BeautifulSoup4

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python test1.py
